/** Whole-page interaction regressions plus HD second-screen hierarchy. */
import assert from 'node:assert/strict';
import {readFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {chromium} from 'playwright-core';
import {serve,root} from './static-server.mjs';
const server=await serve(),browser=await chromium.launch({...(process.env.CHROMIUM?{executablePath:process.env.CHROMIUM}:{}),args:['--no-sandbox']});
const errors=[],widths=[];mkdirSync(join(root,'artifacts'),{recursive:true});
async function open(options={}){const c=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:2,...options});await c.route('**/api.github.com/**',r=>r.fulfill({status:503,body:'{}'}));const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(server.base,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>document.querySelector('#motion-toggle').hidden===false);return {c,p}}
try{
 const css=readFileSync(join(root,'home.css'),'utf8'),js=readFileSync(join(root,'home.js'),'utf8');
 assert.ok(css.includes('border:10px solid var(--ink);border-radius:50%'));assert.ok(css.includes('animation:orbit-spin 6.8s linear infinite'));
 assert.doesNotMatch(css,/cursor\s*:\s*none/);assert.doesNotMatch(js,/addEventListener\(['"]wheel/);assert.doesNotMatch(js,/910|pixelBudget/);
 for(const w of [320,390,768,1024,1280,1440,1920]){const {c,p}=await open({viewport:{width:w,height:w<760?844:900}});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+w);assert.equal(await p.locator('.cursor-aura').evaluate(e=>getComputedStyle(e).pointerEvents),'none');
  const order=await p.evaluate(()=>({first:document.querySelector('main').firstElementChild.className,second:document.querySelector('main').children[1].id,company:document.querySelector('#companies').closest('.hero-fold')!==null,demoWidth:document.querySelector('#hero-demo').getBoundingClientRect().width,companyBottom:document.querySelector('#companies').getBoundingClientRect().bottom}));
  assert.equal(order.first,'hero-fold');assert.equal(order.second,'demo');assert.equal(order.company,true);if(w>=1280)assert.ok(order.demoWidth>=1100,'large HD player at '+w);if(w>=1024)assert.ok(order.companyBottom<=902,'company strip at first-screen bottom '+w);widths.push(w);await c.close();
 }
 const {c,p}=await open();await p.mouse.move(600,300);const card=p.locator('.float-card').first(),r=await card.boundingBox();await p.mouse.move(r.x+r.width/2,r.y+r.height/2);await p.mouse.down();await p.mouse.move(r.x+r.width/2+42,r.y+r.height/2+28,{steps:12});await p.waitForTimeout(220);assert.ok(await card.evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41)>30,'drag follows');await p.mouse.up();await p.mouse.move(600,230);await p.waitForTimeout(1200);assert.ok(Math.abs(await card.evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41))<.3,'spring returns');assert.ok(await p.evaluate(()=>scrollY)<10,'no accidental drag navigation');
 await p.screenshot({path:join(root,'artifacts','desktop-hero.png')});
 const geo=await p.locator('.story').evaluate(e=>({top:e.getBoundingClientRect().top+scrollY,height:e.offsetHeight}));for(const step of [0,1,2,3,1]){await p.evaluate(y=>scrollTo(0,y),geo.top-100+(step/3)*(geo.height-750));await p.waitForTimeout(120);assert.equal(await p.locator('.story-stage').getAttribute('data-step'),String(step));assert.equal(await p.locator('.scene-layer[aria-hidden="false"]').count(),1)}
 await p.locator('#companies').scrollIntoViewIfNeeded();await p.locator('.company-window').focus();const before=await p.locator('.company-track').evaluate(e=>e.style.transform);await p.keyboard.press('ArrowRight');await p.waitForTimeout(80);assert.notEqual(await p.locator('.company-track').evaluate(e=>e.style.transform),before);assert.equal(await p.locator('.company-set[aria-hidden="true"]').count(),1);
 await p.locator('#motion-toggle').click();assert.ok((await p.locator('body').getAttribute('class')).includes('motion-off'));assert.equal(await p.locator('.cursor-aura').evaluate(e=>getComputedStyle(e).display),'none');await p.locator('.story-step').nth(3).click();assert.equal(await p.locator('.story-stage').getAttribute('data-step'),'3');await p.reload();await p.waitForFunction(()=>document.body.classList.contains('motion-off'));await c.close();
 const hd=await open();await hd.p.locator('#hero-demo').evaluate(e=>e.load());await hd.p.waitForFunction(()=>document.querySelector('#hero-demo').readyState>=2);const v=await hd.p.locator('#hero-demo').evaluate(e=>({w:e.videoWidth,h:e.videoHeight,seconds:e.duration,controls:e.controls,inline:e.playsInline,src:e.querySelector('source').getAttribute('src'),poster:e.getAttribute('poster')}));assert.equal(v.w,1920);assert.equal(v.h,1080);assert.ok(v.seconds>35.8&&v.seconds<36.1);assert.equal(v.controls&&v.inline,true);assert.equal(v.src,'media/orbit-demo-hd.mp4');assert.equal(v.poster,'media/orbit-demo-hd-poster.jpg');await hd.p.evaluate(()=>scrollTo(0,document.querySelector('#demo').getBoundingClientRect().top+scrollY-100));await hd.p.locator('#hero-demo').evaluate(e=>{e.pause();e.currentTime=17});await hd.p.waitForTimeout(800);await hd.p.screenshot({path:join(root,'artifacts','desktop-hd-demo.png')});await hd.c.close();
 const mobile=await open({viewport:{width:390,height:844},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 Version/17.0 Mobile/15E148 Safari/604.1'});assert.equal(await mobile.p.locator('#nav-download').getAttribute('href'),'#demo');assert.equal(await mobile.p.locator('.cursor-aura').evaluate(e=>getComputedStyle(e).display),'none');await mobile.p.screenshot({path:join(root,'artifacts','mobile-hero.png')});await mobile.p.locator('.story-step').nth(2).click();assert.equal(await mobile.p.locator('.story-stage').getAttribute('data-step'),'2');await mobile.c.close();
 const red=await open({reducedMotion:'reduce'});assert.ok((await red.p.locator('body').getAttribute('class')).includes('motion-off'));assert.equal(await red.p.locator('#hero-demo').evaluate(e=>e.autoplay),false);await red.c.close();
 const save=await browser.newContext();await save.addInitScript(()=>Object.defineProperty(navigator,'connection',{get:()=>({saveData:true})}));const sp=await save.newPage();await sp.goto(server.base);assert.ok((await sp.locator('body').getAttribute('class')).includes('motion-off'));await save.close();
 const nc=await browser.newContext({javaScriptEnabled:false}),np=await nc.newPage();await np.goto(server.base);assert.ok(await np.locator('h1').isVisible());assert.ok(await np.locator('.scene-layer').first().isVisible());await nc.close();
 const html=readFileSync(join(root,'index.html'),'utf8');assert.match(html,/approximately 90\/hour/);assert.match(html,/Drafts, not confirmed sends/);assert.match(html,/not endorsements or verified offer outcomes/);assert.doesNotMatch(html,/99%|98%|10x faster|offers at|100% accuracy/i);
 assert.deepEqual(errors,[]);console.log('PASS hero: '+widths.join(', ')+'px; first-screen company strip; full-width 1080p second-screen demo; drag, scroll reversal, mobile, accessibility, claims retained.');
}finally{await browser.close();await server.close()}
